apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-config
data:
  PEDIDOS_URL: "http://servico-pedidos:3001"
  PAGAMENTOS_URL: "http://servico-pagamentos:3002"
  ESTOQUE_URL: "http://servico-estoque:3003"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "pedidos"