apiVersion: v1
kind: Secret
metadata:
  name: pedidos-secret
type: Opaque
data:
  # Valores em base64 (codificados)
  # "postgres" em base64 = cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=